name: Create and publish a Docker image

on:
  push:
    tags: ["v*.*.*"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Update Helm chart values
        run: |
          sed -i "s|tag: .*|tag: \"${{ github.ref_name }}\"|" values.yaml

      - name: Set appVersion in Chart.yaml
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/^appVersion: .*/appVersion: \"$VERSION\"/" Chart.yaml
          sed -i "s/^version: .*/version: \"$VERSION\"/" Chart.yaml

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package Helm chart
        run: |
          helm package . --destination packaged

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy packaged chart to gh-pages
        run: |
          mkdir -p gh-pages/charts
          cp packaged/*.tgz gh-pages/charts/

      - name: Generate Helm chart index
        run: |
          helm repo index gh-pages --url https://stefanoverna.github.io/pod-ttl-cleaner

      - name: Commit & push Helm chart
        working-directory: gh-pages
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add charts/*.tgz
          git commit -m "Deploy Helm chart for ${GITHUB_REF#refs/tags/}" || echo "No changes to commit"
          git push origin gh-pages
