name: Create and publish a multi-arch Docker image

on:
  push:
    tags: ['v*.*.*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up QEMU for multi-architecture builds.
      # This allows the runner to emulate ARM64 and other architectures.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx, a CLI plugin that enables multi-platform builds.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push multi-arch Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Set appVersion in Chart.yaml and values.yaml
        # Extracts the version number from the git tag (e.g., v1.2.3 -> 1.2.3)
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/^appVersion: .*/appVersion: \"$VERSION\"/" Chart.yaml
          sed -i "s/^version: .*/version: \"$VERSION\"/" Chart.yaml
          sed -i "s/tag: .*/tag: \"$VERSION\"/" values.yaml

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package Helm chart
        run: |
          helm package . --destination packaged

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy packaged chart to gh-pages
        run: |
          mkdir -p gh-pages/charts
          cp packaged/*.tgz gh-pages/charts/

      - name: Generate Helm chart index
        run: |
          helm repo index gh-pages --url https://stefanoverna.github.io/pod-ttl-cleaner

      - name: Commit & push Helm chart
        working-directory: gh-pages
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add charts/*.tgz index.yaml
          git commit -m "Deploy Helm chart for ${GITHUB_REF#refs/tags/}" || echo "No changes to commit"
          git push origin gh-pages
